# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09ffbe9389068ed5054c7717cf31d74e40c7bf3d67d63de19e3c042a98e87063707530e424827bdac019160cd4be8d4db101678a074e9e4c707728666551a130

test:
  secret_key_base: 8b91ebe545b2433205900e0f52cfc8eefa7095484b8e2221479140e47b6fbef074db4200a52a2aec6829c416a010fa3a16a3054a60f159d16447d2980d568b77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
